models/Application.js
models/EntityAccess.js
models/EntityOpeartion.js
models/Layer.js
models/Role.js
models/ServiceAccess.js
models/User.js
models/UserGroup.js

This introduces the data models as discussed lately.
It also includes some basic implementation for `Role` and `UserGroup` to add more depth to the `*Access` models.
@terrestris/devs please review

Introduces the models

---

package.json

fix(package): update sequelize to version 4.40.0

---

package.json

fix(package): update sequelize-cli to version 5.1.0

---

package.json

fix(package): update sequelize to version 4.41.2

---

package.json

fix(package): update @types/node to version 10.12.9

---

package.json

fix(package): update pg to version 7.7.1

---

package.json

fix(package): update @types/node to version 10.12.14

---

package.json

fix(package): update @types/node to version 10.12.24

---

package.json

fix(package): update @types/node to version 11.9.3

---

package.json

fix(package): update request-promise-native to version 1.0.7

---

package.json

fix(package): update @types/node to version 11.10.4

---

package.json

fix(package): update @types/node to version 11.11.3

---

package.json

fix(package): update @types/sequelize to version 4.27.44

---

package.json

fix(package): update @types/node to version 11.13.0

---

package.json

fix(package): update @types/sequelize to version 4.27.46

---

package.json

fix(package): update ts-node to version 8.2.0

---

package.json

fix(package): update @types/sequelize to version 4.28.3

---

.travis.yml
.vscode/launch.json
package.json

This updates the following packages:
`moment`: 2.22.2 -> 2.24.0
`tslint`: 5.11.0 -> 5.17.0
`typescript`: 3.1.1 -> 3.5.2
This also fixes the config for vscode debugging.

Several package updates

---

package-lock.json
package.json
web/api.ts

- updates `@types/express` to 4.17.1 and fixes the typing
- resolves #143 
@KaiVolland please review

fix types after express update

---

package-lock.json
package.json

Greenkeeper/@types/node 13.1.1
